### ISSUE TITLE
Issue #1 Request Reviews

### ISSUE THREAD

**Issue by SarahRWarren** [pos5737/hw04-sarah-warren#1]
SHA: [098f645](https://github.com/pos5737/hw04-sarah-warren/commit/098f6450843fd15c56742ee9e1bae6de67650294)

Useful Files:
[The .pdf that nearly ended my sanity](https://github.com/pos5737/hw04-sarah-warren/blob/master/Analysis/evaluating_clark_and_goulder_2006.pdf)
[The .tex file that had a remarkably similar effect](https://github.com/pos5737/hw04-sarah-warren/blob/master/Analysis/evaluating_clark_and_goulder_2006.tex)
[The histogram](https://github.com/pos5737/hw04-sarah-warren/tree/master/Analysis/images)
[The R Script I used to Make Said Histogram](https://github.com/pos5737/hw04-sarah-warren/blob/master/R/creating_histograms.R)

Tags
@carlislerainey 
@RichardJSaduners 
@Taylorkchewning

**Comment by taylorkchewning** [comment]
| Topic                     | Excellent     | Satisfactory  | Needs Work          |
|-------------------------  |-----------    |-------------- |-------------------- |
| Substantive claims        |     X         |               |                     |
| Coding style              |              |               |        #2              |
| Coding strategy           |               |              |      #3                |
| Presentation: graphs      |              |              | #2                    |
| Presentation: tables      | -             | -             | -                   |
| Achievement, creativity   |             |     X          |                     |
| Ease of access            |      X         |               |                   |

# Praise
- Your essay was well written and formatted properly in Latex. Specifically, your description of Clark and Golder's (2006) argument stood out, as you analyzed their claims clearly.
- I learned, from reviewing your Latex code, how to center an image in Latex. Further, I learned that Latex uses a similar working directory system to call items to R. This will be helpful for me to know going forward!
- I liked your use of a singular color in your histogram, as well as the simple theme you used. This followed closely with Tufte's (2001) principles to show the data first!

# Other Comments
-  I suggest making some changes to your histogram per our discussions in class. This will improve its aesthetics and readability. [Click here for the details](https://github.com/pos5737/hw04-sarah-warren/issues/2)
- I also suggest using ggsave() to save your images. This will improve the image's resolution and save you time as you won't have to manually save your image every time you make a change. [Click here for more.](https://github.com/pos5737/hw04-sarah-warren/issues/3)

**Comment by SarahRWarren** [comment]
Thanks for the helpful comments, Taylor! I've made the fixes.
